# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts/accounts.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='accounts/accounts.proto',
  package='mruv.accounts',
  syntax='proto3',
  serialized_options=b'Z&github.com/MruV-RP/mruv-pb-go/accounts',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61\x63\x63ounts/accounts.proto\x12\rmruv.accounts\x1a\x1cgoogle/api/annotations.proto\"H\n\x16RegisterAccountRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\">\n\x17RegisterAccountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\naccount_id\x18\x02 \x01(\r\"/\n\x0cLogInRequest\x12\r\n\x05login\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"4\n\rLogInResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x12\n\naccount_id\x18\x02 \x01(\r\"\"\n\x11GetAccountRequest\x12\r\n\x05login\x18\x01 \x01(\t\"2\n\x12GetAccountResponse\x12\r\n\x05login\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\",\n\x1bGetAccountCharactersRequest\x12\r\n\x05login\x18\x01 \x01(\t\"5\n\x1cGetAccountCharactersResponse\x12\x15\n\rcharacter_ids\x18\x01 \x03(\r\"&\n\x15IsAccountExistRequest\x12\r\n\x05login\x18\x01 \x01(\t\"4\n\x16IsAccountExistResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\r2\x8b\x05\n\x13MruVAccountsService\x12\x7f\n\x0fRegisterAccount\x12%.mruv.accounts.RegisterAccountRequest\x1a&.mruv.accounts.RegisterAccountResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\"\x15/v1/accounts/register\x12^\n\x05LogIn\x12\x1b.mruv.accounts.LogInRequest\x1a\x1c.mruv.accounts.LogInResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\"\x12/v1/accounts/login\x12\x86\x01\n\x0eIsAccountExist\x12$.mruv.accounts.IsAccountExistRequest\x1a%.mruv.accounts.IsAccountExistResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/accounts/{login}/registered\x12o\n\nGetAccount\x12 .mruv.accounts.GetAccountRequest\x1a!.mruv.accounts.GetAccountResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/accounts/{login}\x12\x98\x01\n\x14GetAccountCharacters\x12*.mruv.accounts.GetAccountCharactersRequest\x1a+.mruv.accounts.GetAccountCharactersResponse\"\'\x82\xd3\xe4\x93\x02!\x12\x1f/v1/accounts/{login}/charactersB(Z&github.com/MruV-RP/mruv-pb-go/accountsb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_REGISTERACCOUNTREQUEST = _descriptor.Descriptor(
  name='RegisterAccountRequest',
  full_name='mruv.accounts.RegisterAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.RegisterAccountRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='mruv.accounts.RegisterAccountRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='mruv.accounts.RegisterAccountRequest.email', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=144,
)


_REGISTERACCOUNTRESPONSE = _descriptor.Descriptor(
  name='RegisterAccountResponse',
  full_name='mruv.accounts.RegisterAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mruv.accounts.RegisterAccountResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='mruv.accounts.RegisterAccountResponse.account_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=208,
)


_LOGINREQUEST = _descriptor.Descriptor(
  name='LogInRequest',
  full_name='mruv.accounts.LogInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.LogInRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='mruv.accounts.LogInRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=257,
)


_LOGINRESPONSE = _descriptor.Descriptor(
  name='LogInResponse',
  full_name='mruv.accounts.LogInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mruv.accounts.LogInResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='mruv.accounts.LogInResponse.account_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=311,
)


_GETACCOUNTREQUEST = _descriptor.Descriptor(
  name='GetAccountRequest',
  full_name='mruv.accounts.GetAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.GetAccountRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=347,
)


_GETACCOUNTRESPONSE = _descriptor.Descriptor(
  name='GetAccountResponse',
  full_name='mruv.accounts.GetAccountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.GetAccountResponse.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='mruv.accounts.GetAccountResponse.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=399,
)


_GETACCOUNTCHARACTERSREQUEST = _descriptor.Descriptor(
  name='GetAccountCharactersRequest',
  full_name='mruv.accounts.GetAccountCharactersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.GetAccountCharactersRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=445,
)


_GETACCOUNTCHARACTERSRESPONSE = _descriptor.Descriptor(
  name='GetAccountCharactersResponse',
  full_name='mruv.accounts.GetAccountCharactersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='character_ids', full_name='mruv.accounts.GetAccountCharactersResponse.character_ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=500,
)


_ISACCOUNTEXISTREQUEST = _descriptor.Descriptor(
  name='IsAccountExistRequest',
  full_name='mruv.accounts.IsAccountExistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='login', full_name='mruv.accounts.IsAccountExistRequest.login', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=502,
  serialized_end=540,
)


_ISACCOUNTEXISTRESPONSE = _descriptor.Descriptor(
  name='IsAccountExistResponse',
  full_name='mruv.accounts.IsAccountExistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exists', full_name='mruv.accounts.IsAccountExistResponse.exists', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.accounts.IsAccountExistResponse.id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=542,
  serialized_end=594,
)

DESCRIPTOR.message_types_by_name['RegisterAccountRequest'] = _REGISTERACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['RegisterAccountResponse'] = _REGISTERACCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['LogInRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['LogInResponse'] = _LOGINRESPONSE
DESCRIPTOR.message_types_by_name['GetAccountRequest'] = _GETACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetAccountResponse'] = _GETACCOUNTRESPONSE
DESCRIPTOR.message_types_by_name['GetAccountCharactersRequest'] = _GETACCOUNTCHARACTERSREQUEST
DESCRIPTOR.message_types_by_name['GetAccountCharactersResponse'] = _GETACCOUNTCHARACTERSRESPONSE
DESCRIPTOR.message_types_by_name['IsAccountExistRequest'] = _ISACCOUNTEXISTREQUEST
DESCRIPTOR.message_types_by_name['IsAccountExistResponse'] = _ISACCOUNTEXISTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterAccountRequest = _reflection.GeneratedProtocolMessageType('RegisterAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERACCOUNTREQUEST,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.RegisterAccountRequest)
  })
_sym_db.RegisterMessage(RegisterAccountRequest)

RegisterAccountResponse = _reflection.GeneratedProtocolMessageType('RegisterAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERACCOUNTRESPONSE,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.RegisterAccountResponse)
  })
_sym_db.RegisterMessage(RegisterAccountResponse)

LogInRequest = _reflection.GeneratedProtocolMessageType('LogInRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGINREQUEST,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.LogInRequest)
  })
_sym_db.RegisterMessage(LogInRequest)

LogInResponse = _reflection.GeneratedProtocolMessageType('LogInResponse', (_message.Message,), {
  'DESCRIPTOR' : _LOGINRESPONSE,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.LogInResponse)
  })
_sym_db.RegisterMessage(LogInResponse)

GetAccountRequest = _reflection.GeneratedProtocolMessageType('GetAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTREQUEST,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.GetAccountRequest)
  })
_sym_db.RegisterMessage(GetAccountRequest)

GetAccountResponse = _reflection.GeneratedProtocolMessageType('GetAccountResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTRESPONSE,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.GetAccountResponse)
  })
_sym_db.RegisterMessage(GetAccountResponse)

GetAccountCharactersRequest = _reflection.GeneratedProtocolMessageType('GetAccountCharactersRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTCHARACTERSREQUEST,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.GetAccountCharactersRequest)
  })
_sym_db.RegisterMessage(GetAccountCharactersRequest)

GetAccountCharactersResponse = _reflection.GeneratedProtocolMessageType('GetAccountCharactersResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETACCOUNTCHARACTERSRESPONSE,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.GetAccountCharactersResponse)
  })
_sym_db.RegisterMessage(GetAccountCharactersResponse)

IsAccountExistRequest = _reflection.GeneratedProtocolMessageType('IsAccountExistRequest', (_message.Message,), {
  'DESCRIPTOR' : _ISACCOUNTEXISTREQUEST,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.IsAccountExistRequest)
  })
_sym_db.RegisterMessage(IsAccountExistRequest)

IsAccountExistResponse = _reflection.GeneratedProtocolMessageType('IsAccountExistResponse', (_message.Message,), {
  'DESCRIPTOR' : _ISACCOUNTEXISTRESPONSE,
  '__module__' : 'accounts.accounts_pb2'
  # @@protoc_insertion_point(class_scope:mruv.accounts.IsAccountExistResponse)
  })
_sym_db.RegisterMessage(IsAccountExistResponse)


DESCRIPTOR._options = None

_MRUVACCOUNTSSERVICE = _descriptor.ServiceDescriptor(
  name='MruVAccountsService',
  full_name='mruv.accounts.MruVAccountsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=597,
  serialized_end=1248,
  methods=[
  _descriptor.MethodDescriptor(
    name='RegisterAccount',
    full_name='mruv.accounts.MruVAccountsService.RegisterAccount',
    index=0,
    containing_service=None,
    input_type=_REGISTERACCOUNTREQUEST,
    output_type=_REGISTERACCOUNTRESPONSE,
    serialized_options=b'\202\323\344\223\002\027\"\025/v1/accounts/register',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LogIn',
    full_name='mruv.accounts.MruVAccountsService.LogIn',
    index=1,
    containing_service=None,
    input_type=_LOGINREQUEST,
    output_type=_LOGINRESPONSE,
    serialized_options=b'\202\323\344\223\002\024\"\022/v1/accounts/login',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsAccountExist',
    full_name='mruv.accounts.MruVAccountsService.IsAccountExist',
    index=2,
    containing_service=None,
    input_type=_ISACCOUNTEXISTREQUEST,
    output_type=_ISACCOUNTEXISTRESPONSE,
    serialized_options=b'\202\323\344\223\002!\022\037/v1/accounts/{login}/registered',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccount',
    full_name='mruv.accounts.MruVAccountsService.GetAccount',
    index=3,
    containing_service=None,
    input_type=_GETACCOUNTREQUEST,
    output_type=_GETACCOUNTRESPONSE,
    serialized_options=b'\202\323\344\223\002\026\022\024/v1/accounts/{login}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccountCharacters',
    full_name='mruv.accounts.MruVAccountsService.GetAccountCharacters',
    index=4,
    containing_service=None,
    input_type=_GETACCOUNTCHARACTERSREQUEST,
    output_type=_GETACCOUNTCHARACTERSRESPONSE,
    serialized_options=b'\202\323\344\223\002!\022\037/v1/accounts/{login}/characters',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MRUVACCOUNTSSERVICE)

DESCRIPTOR.services_by_name['MruVAccountsService'] = _MRUVACCOUNTSSERVICE

# @@protoc_insertion_point(module_scope)
