# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from objects import objects_pb2 as objects_dot_objects__pb2


class MruVObjectsServiceStub(object):
  """The MruV objects service provides procedures for game objects.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateObject = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/CreateObject',
        request_serializer=objects_dot_objects__pb2.CreateObjectRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.CreateObjectResponse.FromString,
        )
    self.GetObject = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/GetObject',
        request_serializer=objects_dot_objects__pb2.GetObjectRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.GetObjectResponse.FromString,
        )
    self.UpdateObject = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/UpdateObject',
        request_serializer=objects_dot_objects__pb2.UpdateObjectRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.UpdateObjectResponse.FromString,
        )
    self.DeleteObject = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/DeleteObject',
        request_serializer=objects_dot_objects__pb2.DeleteObjectRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.DeleteObjectResponse.FromString,
        )
    self.AddObjectMaterial = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/AddObjectMaterial',
        request_serializer=objects_dot_objects__pb2.AddObjectMaterialRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.AddObjectMaterialResponse.FromString,
        )
    self.GetObjectMaterials = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/GetObjectMaterials',
        request_serializer=objects_dot_objects__pb2.GetObjectMaterialsRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.GetObjectMaterialsResponse.FromString,
        )
    self.DeleteObjectMaterial = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/DeleteObjectMaterial',
        request_serializer=objects_dot_objects__pb2.DeleteObjectMaterialRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.DeleteObjectMaterialResponse.FromString,
        )
    self.AddObjectMaterialText = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/AddObjectMaterialText',
        request_serializer=objects_dot_objects__pb2.AddObjectMaterialTextRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.AddObjectMaterialTextResponse.FromString,
        )
    self.GetObjectMaterialTexts = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/GetObjectMaterialTexts',
        request_serializer=objects_dot_objects__pb2.GetObjectMaterialTextsRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.GetObjectMaterialTextsResponse.FromString,
        )
    self.DeleteObjectMaterialText = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/DeleteObjectMaterialText',
        request_serializer=objects_dot_objects__pb2.DeleteObjectMaterialTextRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.DeleteObjectMaterialTextResponse.FromString,
        )
    self.AddRemoveBuilding = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/AddRemoveBuilding',
        request_serializer=objects_dot_objects__pb2.AddRemoveBuildingRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.AddRemoveBuildingResponse.FromString,
        )
    self.GetRemovedBuildings = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/GetRemovedBuildings',
        request_serializer=objects_dot_objects__pb2.GetRemovedBuildingsRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.GetRemovedBuildingsResponse.FromString,
        )
    self.DeleteRemoveBuilding = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/DeleteRemoveBuilding',
        request_serializer=objects_dot_objects__pb2.DeleteRemoveBuildingRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.DeleteRemoveBuildingResponse.FromString,
        )
    self.FetchAll = channel.unary_unary(
        '/mruv.objects.MruVObjectsService/FetchAll',
        request_serializer=objects_dot_objects__pb2.FetchAllRequest.SerializeToString,
        response_deserializer=objects_dot_objects__pb2.FetchAllResponse.FromString,
        )


class MruVObjectsServiceServicer(object):
  """The MruV objects service provides procedures for game objects.
  """

  def CreateObject(self, request, context):
    """Create an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObject(self, request, context):
    """Get an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateObject(self, request, context):
    """Update an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteObject(self, request, context):
    """Delete an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddObjectMaterial(self, request, context):
    """Add a material to existing object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObjectMaterials(self, request, context):
    """Get all object materials.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteObjectMaterial(self, request, context):
    """Delete a material assigned to an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddObjectMaterialText(self, request, context):
    """Add a material text to existing object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetObjectMaterialTexts(self, request, context):
    """Get all object material texts.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteObjectMaterialText(self, request, context):
    """Delete a material text assigned to an object.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddRemoveBuilding(self, request, context):
    """Removes a object from GTA SA map.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetRemovedBuildings(self, request, context):
    """Get all removed objects.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteRemoveBuilding(self, request, context):
    """Delete removed buildings.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchAll(self, request, context):
    """Fetch all existing objects.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MruVObjectsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateObject': grpc.unary_unary_rpc_method_handler(
          servicer.CreateObject,
          request_deserializer=objects_dot_objects__pb2.CreateObjectRequest.FromString,
          response_serializer=objects_dot_objects__pb2.CreateObjectResponse.SerializeToString,
      ),
      'GetObject': grpc.unary_unary_rpc_method_handler(
          servicer.GetObject,
          request_deserializer=objects_dot_objects__pb2.GetObjectRequest.FromString,
          response_serializer=objects_dot_objects__pb2.GetObjectResponse.SerializeToString,
      ),
      'UpdateObject': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateObject,
          request_deserializer=objects_dot_objects__pb2.UpdateObjectRequest.FromString,
          response_serializer=objects_dot_objects__pb2.UpdateObjectResponse.SerializeToString,
      ),
      'DeleteObject': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteObject,
          request_deserializer=objects_dot_objects__pb2.DeleteObjectRequest.FromString,
          response_serializer=objects_dot_objects__pb2.DeleteObjectResponse.SerializeToString,
      ),
      'AddObjectMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.AddObjectMaterial,
          request_deserializer=objects_dot_objects__pb2.AddObjectMaterialRequest.FromString,
          response_serializer=objects_dot_objects__pb2.AddObjectMaterialResponse.SerializeToString,
      ),
      'GetObjectMaterials': grpc.unary_unary_rpc_method_handler(
          servicer.GetObjectMaterials,
          request_deserializer=objects_dot_objects__pb2.GetObjectMaterialsRequest.FromString,
          response_serializer=objects_dot_objects__pb2.GetObjectMaterialsResponse.SerializeToString,
      ),
      'DeleteObjectMaterial': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteObjectMaterial,
          request_deserializer=objects_dot_objects__pb2.DeleteObjectMaterialRequest.FromString,
          response_serializer=objects_dot_objects__pb2.DeleteObjectMaterialResponse.SerializeToString,
      ),
      'AddObjectMaterialText': grpc.unary_unary_rpc_method_handler(
          servicer.AddObjectMaterialText,
          request_deserializer=objects_dot_objects__pb2.AddObjectMaterialTextRequest.FromString,
          response_serializer=objects_dot_objects__pb2.AddObjectMaterialTextResponse.SerializeToString,
      ),
      'GetObjectMaterialTexts': grpc.unary_unary_rpc_method_handler(
          servicer.GetObjectMaterialTexts,
          request_deserializer=objects_dot_objects__pb2.GetObjectMaterialTextsRequest.FromString,
          response_serializer=objects_dot_objects__pb2.GetObjectMaterialTextsResponse.SerializeToString,
      ),
      'DeleteObjectMaterialText': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteObjectMaterialText,
          request_deserializer=objects_dot_objects__pb2.DeleteObjectMaterialTextRequest.FromString,
          response_serializer=objects_dot_objects__pb2.DeleteObjectMaterialTextResponse.SerializeToString,
      ),
      'AddRemoveBuilding': grpc.unary_unary_rpc_method_handler(
          servicer.AddRemoveBuilding,
          request_deserializer=objects_dot_objects__pb2.AddRemoveBuildingRequest.FromString,
          response_serializer=objects_dot_objects__pb2.AddRemoveBuildingResponse.SerializeToString,
      ),
      'GetRemovedBuildings': grpc.unary_unary_rpc_method_handler(
          servicer.GetRemovedBuildings,
          request_deserializer=objects_dot_objects__pb2.GetRemovedBuildingsRequest.FromString,
          response_serializer=objects_dot_objects__pb2.GetRemovedBuildingsResponse.SerializeToString,
      ),
      'DeleteRemoveBuilding': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteRemoveBuilding,
          request_deserializer=objects_dot_objects__pb2.DeleteRemoveBuildingRequest.FromString,
          response_serializer=objects_dot_objects__pb2.DeleteRemoveBuildingResponse.SerializeToString,
      ),
      'FetchAll': grpc.unary_unary_rpc_method_handler(
          servicer.FetchAll,
          request_deserializer=objects_dot_objects__pb2.FetchAllRequest.FromString,
          response_serializer=objects_dot_objects__pb2.FetchAllResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'mruv.objects.MruVObjectsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
