# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: offers/offers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='offers/offers.proto',
  package='mruv.offers',
  syntax='proto3',
  serialized_options=b'Z$github.com/MruV-RP/mruv-pb-go/offers',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13offers/offers.proto\x12\x0bmruv.offers\x1a\x1cgoogle/api/annotations.proto\"\xac\x01\n\x12\x43reateOfferRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05offer\x18\x03 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x04 \x01(\x03\x12\r\n\x05price\x18\x05 \x01(\r\x12*\n\noffer_type\x18\x06 \x01(\x0e\x32\x16.mruv.offers.OfferType\x12\x17\n\x0foffer_entity_id\x18\x07 \x01(\r\"!\n\x13\x43reateOfferResponse\x12\n\n\x02id\x18\x01 \x01(\r\"\x1d\n\x0fGetOfferRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x12\n\x10GetOfferResponse\" \n\x12UpdateOfferRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x15\n\x13UpdateOfferResponse\" \n\x12\x44\x65leteOfferRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x15\n\x13\x44\x65leteOfferResponse\" \n\x12\x41\x63\x63\x65ptOfferRequest\x12\n\n\x02id\x18\x01 \x01(\r\"\x15\n\x13\x41\x63\x63\x65ptOfferResponse*\x18\n\tOfferType\x12\x0b\n\x07UNKNOWN\x10\x00\x32\xac\x04\n\x11MruVOffersService\x12g\n\x0b\x43reateOffer\x12\x1f.mruv.offers.CreateOfferRequest\x1a .mruv.offers.CreateOfferResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/v1/offers:\x01*\x12`\n\x08GetOffer\x12\x1c.mruv.offers.GetOfferRequest\x1a\x1d.mruv.offers.GetOfferResponse\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/offers/{id}\x12l\n\x0bUpdateOffer\x12\x1f.mruv.offers.UpdateOfferRequest\x1a .mruv.offers.UpdateOfferResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x32\x0f/v1/offers/{id}:\x01*\x12i\n\x0b\x44\x65leteOffer\x12\x1f.mruv.offers.DeleteOfferRequest\x1a .mruv.offers.DeleteOfferResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/offers/{id}\x12s\n\x0b\x41\x63\x63\x65ptOffer\x12\x1f.mruv.offers.AcceptOfferRequest\x1a .mruv.offers.AcceptOfferResponse\"!\x82\xd3\xe4\x93\x02\x1b\"\x16/v1/offers/{id}/accept:\x01*B&Z$github.com/MruV-RP/mruv-pb-go/offersb\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])

_OFFERTYPE = _descriptor.EnumDescriptor(
  name='OfferType',
  full_name='mruv.offers.OfferType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=498,
  serialized_end=522,
)
_sym_db.RegisterEnumDescriptor(_OFFERTYPE)

OfferType = enum_type_wrapper.EnumTypeWrapper(_OFFERTYPE)
UNKNOWN = 0



_CREATEOFFERREQUEST = _descriptor.Descriptor(
  name='CreateOfferRequest',
  full_name='mruv.offers.CreateOfferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='mruv.offers.CreateOfferRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='mruv.offers.CreateOfferRequest.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offer', full_name='mruv.offers.CreateOfferRequest.offer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='mruv.offers.CreateOfferRequest.end_date', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='mruv.offers.CreateOfferRequest.price', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offer_type', full_name='mruv.offers.CreateOfferRequest.offer_type', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='offer_entity_id', full_name='mruv.offers.CreateOfferRequest.offer_entity_id', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=239,
)


_CREATEOFFERRESPONSE = _descriptor.Descriptor(
  name='CreateOfferResponse',
  full_name='mruv.offers.CreateOfferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.offers.CreateOfferResponse.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=274,
)


_GETOFFERREQUEST = _descriptor.Descriptor(
  name='GetOfferRequest',
  full_name='mruv.offers.GetOfferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.offers.GetOfferRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=305,
)


_GETOFFERRESPONSE = _descriptor.Descriptor(
  name='GetOfferResponse',
  full_name='mruv.offers.GetOfferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=325,
)


_UPDATEOFFERREQUEST = _descriptor.Descriptor(
  name='UpdateOfferRequest',
  full_name='mruv.offers.UpdateOfferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.offers.UpdateOfferRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=359,
)


_UPDATEOFFERRESPONSE = _descriptor.Descriptor(
  name='UpdateOfferResponse',
  full_name='mruv.offers.UpdateOfferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=361,
  serialized_end=382,
)


_DELETEOFFERREQUEST = _descriptor.Descriptor(
  name='DeleteOfferRequest',
  full_name='mruv.offers.DeleteOfferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.offers.DeleteOfferRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=416,
)


_DELETEOFFERRESPONSE = _descriptor.Descriptor(
  name='DeleteOfferResponse',
  full_name='mruv.offers.DeleteOfferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=439,
)


_ACCEPTOFFERREQUEST = _descriptor.Descriptor(
  name='AcceptOfferRequest',
  full_name='mruv.offers.AcceptOfferRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='mruv.offers.AcceptOfferRequest.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=473,
)


_ACCEPTOFFERRESPONSE = _descriptor.Descriptor(
  name='AcceptOfferResponse',
  full_name='mruv.offers.AcceptOfferResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=475,
  serialized_end=496,
)

_CREATEOFFERREQUEST.fields_by_name['offer_type'].enum_type = _OFFERTYPE
DESCRIPTOR.message_types_by_name['CreateOfferRequest'] = _CREATEOFFERREQUEST
DESCRIPTOR.message_types_by_name['CreateOfferResponse'] = _CREATEOFFERRESPONSE
DESCRIPTOR.message_types_by_name['GetOfferRequest'] = _GETOFFERREQUEST
DESCRIPTOR.message_types_by_name['GetOfferResponse'] = _GETOFFERRESPONSE
DESCRIPTOR.message_types_by_name['UpdateOfferRequest'] = _UPDATEOFFERREQUEST
DESCRIPTOR.message_types_by_name['UpdateOfferResponse'] = _UPDATEOFFERRESPONSE
DESCRIPTOR.message_types_by_name['DeleteOfferRequest'] = _DELETEOFFERREQUEST
DESCRIPTOR.message_types_by_name['DeleteOfferResponse'] = _DELETEOFFERRESPONSE
DESCRIPTOR.message_types_by_name['AcceptOfferRequest'] = _ACCEPTOFFERREQUEST
DESCRIPTOR.message_types_by_name['AcceptOfferResponse'] = _ACCEPTOFFERRESPONSE
DESCRIPTOR.enum_types_by_name['OfferType'] = _OFFERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateOfferRequest = _reflection.GeneratedProtocolMessageType('CreateOfferRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEOFFERREQUEST,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.CreateOfferRequest)
  })
_sym_db.RegisterMessage(CreateOfferRequest)

CreateOfferResponse = _reflection.GeneratedProtocolMessageType('CreateOfferResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEOFFERRESPONSE,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.CreateOfferResponse)
  })
_sym_db.RegisterMessage(CreateOfferResponse)

GetOfferRequest = _reflection.GeneratedProtocolMessageType('GetOfferRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOFFERREQUEST,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.GetOfferRequest)
  })
_sym_db.RegisterMessage(GetOfferRequest)

GetOfferResponse = _reflection.GeneratedProtocolMessageType('GetOfferResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOFFERRESPONSE,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.GetOfferResponse)
  })
_sym_db.RegisterMessage(GetOfferResponse)

UpdateOfferRequest = _reflection.GeneratedProtocolMessageType('UpdateOfferRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEOFFERREQUEST,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.UpdateOfferRequest)
  })
_sym_db.RegisterMessage(UpdateOfferRequest)

UpdateOfferResponse = _reflection.GeneratedProtocolMessageType('UpdateOfferResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEOFFERRESPONSE,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.UpdateOfferResponse)
  })
_sym_db.RegisterMessage(UpdateOfferResponse)

DeleteOfferRequest = _reflection.GeneratedProtocolMessageType('DeleteOfferRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEOFFERREQUEST,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.DeleteOfferRequest)
  })
_sym_db.RegisterMessage(DeleteOfferRequest)

DeleteOfferResponse = _reflection.GeneratedProtocolMessageType('DeleteOfferResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEOFFERRESPONSE,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.DeleteOfferResponse)
  })
_sym_db.RegisterMessage(DeleteOfferResponse)

AcceptOfferRequest = _reflection.GeneratedProtocolMessageType('AcceptOfferRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTOFFERREQUEST,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.AcceptOfferRequest)
  })
_sym_db.RegisterMessage(AcceptOfferRequest)

AcceptOfferResponse = _reflection.GeneratedProtocolMessageType('AcceptOfferResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTOFFERRESPONSE,
  '__module__' : 'offers.offers_pb2'
  # @@protoc_insertion_point(class_scope:mruv.offers.AcceptOfferResponse)
  })
_sym_db.RegisterMessage(AcceptOfferResponse)


DESCRIPTOR._options = None

_MRUVOFFERSSERVICE = _descriptor.ServiceDescriptor(
  name='MruVOffersService',
  full_name='mruv.offers.MruVOffersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=525,
  serialized_end=1081,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateOffer',
    full_name='mruv.offers.MruVOffersService.CreateOffer',
    index=0,
    containing_service=None,
    input_type=_CREATEOFFERREQUEST,
    output_type=_CREATEOFFERRESPONSE,
    serialized_options=b'\202\323\344\223\002\017\"\n/v1/offers:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetOffer',
    full_name='mruv.offers.MruVOffersService.GetOffer',
    index=1,
    containing_service=None,
    input_type=_GETOFFERREQUEST,
    output_type=_GETOFFERRESPONSE,
    serialized_options=b'\202\323\344\223\002\021\022\017/v1/offers/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateOffer',
    full_name='mruv.offers.MruVOffersService.UpdateOffer',
    index=2,
    containing_service=None,
    input_type=_UPDATEOFFERREQUEST,
    output_type=_UPDATEOFFERRESPONSE,
    serialized_options=b'\202\323\344\223\002\0242\017/v1/offers/{id}:\001*',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteOffer',
    full_name='mruv.offers.MruVOffersService.DeleteOffer',
    index=3,
    containing_service=None,
    input_type=_DELETEOFFERREQUEST,
    output_type=_DELETEOFFERRESPONSE,
    serialized_options=b'\202\323\344\223\002\021*\017/v1/offers/{id}',
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AcceptOffer',
    full_name='mruv.offers.MruVOffersService.AcceptOffer',
    index=4,
    containing_service=None,
    input_type=_ACCEPTOFFERREQUEST,
    output_type=_ACCEPTOFFERRESPONSE,
    serialized_options=b'\202\323\344\223\002\033\"\026/v1/offers/{id}/accept:\001*',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MRUVOFFERSSERVICE)

DESCRIPTOR.services_by_name['MruVOffersService'] = _MRUVOFFERSSERVICE

# @@protoc_insertion_point(module_scope)
